version: "3.8"           # Docker-compose 파일 버전

services:
  mysql:                 # 사용할 서비스 명
    container_name: mysql_local
    build: .
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=pass_local_user
      - MYSQL_PASSWORD=passlocal123
      - MYSQL_ROOT_PASSWORD=passlocal123
      - TZ=Asia/Seoul